create table urls (
                      id                            bigint generated by default as identity not null,
                      protocol                      varchar(255),
                      host                          varchar(255),
                      port                          integer,
                      created_at                    timestamptz not null,
                      constraint pk_urls primary key (id)
);

create table url_check (
                           id                            bigint generated by default as identity not null,
                           status_code                   integer default 0 not null,
                           title                         varchar(255),
                           h1                            varchar(255),
                           description                   text,
                           urls_id                       bigint not null,
                           created_at                    timestamptz not null,
                           constraint pk_url_check primary key (id)
);

create index ix_url_check_urls_id on url_check (urls_id); 
alter table url_check add constraint fk_url_check_urls_id foreign key (urls_id) references urls (id) on delete restrict on update restrict;

